version: '3.2'

services:
  elasticsearch:
    image: elasticsearch:7.9.3
    container_name: elasticsearch
    volumes:
      - type: bind
        source: ./elasticsearch.yml
        target: /usr/share/elasticsearch/config/elasticsearch.yml
        read_only: true
      - type: volume
        source: elasticsearch
        target: /usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
      # Use single node discovery in order to disable production mode and avoid bootstrap checks.
      # see: https://www.elastic.co/guide/en/elasticsearch/reference/current/bootstrap-checks.html
      discovery.type: single-node
    networks:
      - elk

  kibana:
    image: kibana:7.9.3
    container_name: kibana
    volumes:
      - type: bind
        source: ./kibana.yml
        target: /usr/share/kibana/config/kibana.yml
        read_only: true
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    ports:
      - "5601:5601"
    networks:
      - elk
    depends_on:
      - elasticsearch

  dataloader:
    image: maxvale/psl-connector:0.1
#    build:
#      context: ../../../
#      dockerfile: ./build/Dockerfiles/Dockerfile.local
    container_name: dataloader
    volumes:
      - type: bind
        source: ./config.yaml
        target: /go/connector/app/config.yaml
        read_only: true
    entrypoint: ["/go/connector/app/utils/startup.sh"]
    networks:
      - elk
    depends_on:
      - elasticsearch

networks:
  elk:
    driver: bridge

volumes:
  elasticsearch: