output:
  format: colored-line-number

linters-settings:
  lll:
    line-length: 250
  funlen:
    lines: 220
    statements: 110
  gocognit:
    min-complexity: 60

linters:
  disable-all: true
  enable:
    - bodyclose
    - deadcode
    - depguard
    - dogsled
    - errcheck
    - funlen
    - gochecknoinits
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - golint
    - gosimple
    - govet
    - ineffassign
    - interfacer
    - lll
    - megacheck
    - misspell
    - nakedret
    - scopelint
    - staticcheck
    - structcheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - varcheck
    - whitespace
    - maligned
    - prealloc
    - dupl
    - wsl
    - gosec
